#!/bin/sh

log() {
	printf '\033[38;5;%sm%s\033[m: %s.\n' "$@" >&2
}

err() {
	log 1 error "$*"
	exit 1
}

prompt() {
	printf '%s? [y/N] ' "${1:-Continue}"
	read -r input
	[ "$input" = y ] || [ "$input" = Y ]
}

cp() {
	printf '# cp %s\n' "$*"
	command cp "$@"
}

mv() {
	printf '# mv %s\n' "$*"
	command mv "$@"
}

mkdir() {
	printf '# mkdir -p %s\n' "$*"
	command mkdir -p "$@"
}

main() {
	# shitty error handling
	if [ -z "$1" ]; then
		log 3 help "Usage: ${0##*/} [repo directory]"
		exit 2
	fi

	if [ "$(id -u)" -ne 0 ]; then
		err 'Launch as root'
	fi

	case $PWD in
		/home/*) homedir=$PWD ;;
		*) err 'Must be in ~ in order to copy some things' ;;
	esac

	: "${XDG_DATA_HOME:=$homedir/.local/share}"
	: "${XDG_CONFIG_HOME:=$homedir/.config}"

	# do the thing
	cd -- "$1" || exit 1

	for dir in /usr/lib/qt /usr/lib/x86_64-linux-gnu/qt5; do
		[ -d "$dir" ] && break
	done
	pluginsdir=$dir/plugins
	mkdir \
		"$XDG_DATA_HOME/icons" \
		"$XDG_DATA_HOME/themes" \
		"$XDG_DATA_HOME/plasma/desktoptheme" \
		"$XDG_DATA_HOME/plasma/plasmoids" \
		"$pluginsdir/org.kde.kdecoration2" \
		"$pluginsdir/plasma/applets"

	cp -r 'Icons and cursors/'* "$XDG_DATA_HOME/icons"
	cp -r 'Qt/Application Theme/QGtkStyle/win27pixmap' "$XDG_DATA_HOME/themes"
	cp -r 'Plasma/KDE Plasma Theme/Seven-Black' "$XDG_DATA_HOME/plasma/desktoptheme"
	for dir in \
		'Date and Time/org.kde.plasma.digitalclocklite' \
		'Show Desktop/org.kde.plasma.win7showdesktop' \
		'Task Icons/org.kde.plasma.seventasks' \
		'Start Menu/SevenStart'
	do
		dir="Plasma/Plasma Widgets/User/$dir"

		if [ -d "$dir" ]; then
			cp -r "$dir" "$XDG_DATA_HOME/plasma/plasmoids"
		fi
	done

	cp -r KWin/.emerald "$homedir"
	cp KWin/bin/kwin_smaragd.so "$pluginsdir/org.kde.kdecoration2"
	cp 'Plasma/Plasma Widgets/User/Task Icons/bin/plasma_applet_seventasks.so' "$pluginsdir/plasma/applets"

	# AeroColorMixer
	aerocolormixer='Plasma/KDE Plasma Theme/AeroColorMixer/build/AeroColorMixer'
	if prompt 'Install AeroColorMixer'; then
		# Check if it runs
		if "$aerocolormixer" & (:;:); kill "$!"; then
			cp "$aerocolormixer" /usr/local/bin
		else
			if prompt 'Compile AeroColorMixer'; then
				# do the thing, idk
			fi
		fi
	fi

	# system modifications
	log 3 warn 'The next step will replace/modify system files - this may break KDE as a result'
	log 4 note 'These changes will be reset after each system update'
	log 4 note 'Backups will be made under the same name with -backup'
	if prompt; then
		for i in \
			'System Tray/org.kde.plasma.private.systemtray' \
			'Keyboard Switcher/org.kde.plasma.keyboardlayout' \
			'Desktop Icons/org.kde.desktopcontainment'
		do
			widgetdir=/usr/share/plasma/plasmoids/${i##*/}

			mv "$widgetdir" "$widgetdir-backup"
			cp -r "Plasma/Plasma Widgets/System/$i" "$widgetdir"
		done

		tooltipsdir=${pluginsdir%/*}/qml/org/kde/plasma/core/private
		mv "$tooltipsdir/DefaultTooltip.qml" "$tooltipsdir/DefaultTooltip.qml-backup"
		mv 'Plasma/Plasma Widgets/System/Tooltips/DefaultTooltip.qml' "$tooltipsdir"
	fi

	# restart
	if prompt 'Restart KDE'; then
		su "${homedir#/home/}" sh -c 'kwin_x11 --replace & plasmashell --replace &'
	fi
}

main "$@"
